### ISSUE TITLE
Merged graphs are weird

### ISSUE THREAD

**Issue by gedankenstuecke** [openSNP/growthplots#1]
The merged graphs for two datasets seem to miss some data somehow, have to investigate this!

**Comment by gedankenstuecke** [comment]
Ok, there's still this issue that data is somehow absent if you plot it like this: 

![geno_plus_phenotypes](https://cloud.githubusercontent.com/assets/674899/13258922/70989d56-da55-11e5-8206-8f101021c4fb.png)

Before merging the two data frames they look fine: 
![genotypes](https://cloud.githubusercontent.com/assets/674899/13258946/89cd97ae-da55-11e5-9ef4-fc112323b2a8.png)
![users](https://cloud.githubusercontent.com/assets/674899/13258966/9e1142ce-da55-11e5-8f3b-1e9ec97f9aee.png)

Does anyone of you have an idea why that's the case?

**Comment by philippbayer** [comment]
![geno_plus_phenotypes](https://cloud.githubusercontent.com/assets/413885/13370581/1837fd4c-dd47-11e5-8eaa-d78988b4ff10.png)

Looks good to me!

**Comment by gedankenstuecke** [comment]
Perfect! :+1:
